language: ruby
rvm:
  - 1.8.7
  - 1.9.3

before_install:
  - gem update --system
  - rvm @default,@global do gem uninstall -ax bundler
  - gem install bundle --pre
  - bundle --version  

before_script:
  - mongo mydb_test --eval 'db.addUser("travis", "test");'

